In [3]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
%matplotlib inline

In [54]:
## Nome dos paths onse estão salvos e vamos salvar os dados processados
PATH_FAIXA_ETARIAS = '../dados/faixa_etaria/' # Nome do path dos arquivos salvos
FILENAME_FAIXA_ETARIAS = 'faixas_etarias_2020.csv'
dfFE = pd.read_csv(PATH_FAIXA_ETARIAS + FILENAME_FAIXA_ETARIAS, encoding='utf-8', delimiter=';')

In [55]:
dfFE

,Grupo Etário,RO - MASCULINO,AC - MASCULINO,AM - MASCULINO,RR - MASCULINO,PA - MASCULINO,AP - MASCULINO,TO - MASCULINO,MA - MASCULINO,PI - MASCULINO,...,ES - FEMININO,RJ - FEMININO,SP - FEMININO,PR - FEMININO,SC - FEMININO,RS - FEMININO,MS - FEMININO,MT - FEMININO,GO - FEMININO,DF - FEMININO
0,0 - 4,71586,42476,206480,30420,366755,41039,64155,300256,121499,...,140509,548521,1483786,384972,237651,345608,107071,138421,252012,100329
1,5 - 9,69560,43387,208071,28355,373651,41211,64187,300367,120959,...,138812,537734,1486357,375728,227142,339418,105511,131929,254480,91892
2,10 - 14,70266,45549,203933,27243,402480,41305,67383,334635,130911,...,133867,515868,1446086,367729,218251,328332,99186,131081,242481,101287
3,15 - 19,76484,47019,197868,27174,412106,42614,69580,338987,145234,...,143330,558014,1531720,396227,230601,373858,101276,131744,255582,118022
4,20 - 24,79509,44217,204323,31733,415784,41958,73140,340010,146827,...,155809,659464,1701929,448731,273363,422176,110382,139827,284906,126328
5,25 - 29,78871,38048,183809,33377,382715,39514,69129,296825,129267,...,157794,656296,1738870,459489,292575,429436,113865,144384,295305,129515
6,30 - 34,78422,34758,170665,31403,362389,36746,65336,283326,126204,...,168318,674666,1888809,448377,301175,425981,111444,144724,301927,136814
7,35 - 39,74905,32843,159925,28172,341196,32957,62308,265498,120875,...,167709,705901,1946363,443789,297353,442017,111864,141970,296964,147312
8,40 - 44,66545,28431,139640,22877,299664,27963,56795,227704,111510,...,155595,684994,1822081,426104,266593,404906,102843,132077,279953,137800
9,45 - 49,56831,22995,113517,17867,248902,23525,47826,183499,93629,...,134337,617789,1628117,400442,244853,374148,92294,115814,246741,114163
10,50 - 54,51997,18924,94307,14335,207905,18868,41306,158430,84794,...,125801,587438,1517168,388798,238948,383384,84886,102597,221423,98898
11,55 - 59,43973,14600,74524,11385,164448,14472,34073,130761,72879,...,116037,564885,1407141,354699,225919,387394,77222,86653,188322,83156
12,60 - 64,33258,11434,56217,8405,131093,11020,26889,104514,58113,...,100133,506991,1228204,296643,184738,343373,62249,67912,151504,65073
13,65 - 69,23038,8620,39956,5940,97428,7470,21052,82423,45604,...,78423,413660,979409,237497,146058,283873,48036,49723,116263,49890
14,70 - 74,15009,6023,25993,3899,66012,4589,15239,60639,34580,...,54647,312473,732830,176239,106080,217814,34557,34236,82669,35620
15,75 - 79,9093,3860,16721,2117,42858,3103,10412,41663,22844,...,38129,211929,495222,121357,70570,151553,24104,22192,55072,22931
16,80 - 84,5255,2227,9299,1109,23931,1734,6698,25747,13619,...,26663,148646,341634,79106,47287,104225,15549,13574,35225,14999
17,85 - 89,2327,1169,4517,467,11300,862,3337,13188,6177,...,15668,87719,197189,43777,26376,62028,8252,6550,17735,7463
18,90+,1240,740,2363,217,6034,544,1644,7956,3132,...,11857,66930,144091,25838,18854,44979,4993,3835,9707,4279

In [61]:
# colSelFE = [col for col in dfFE.columns if col.startswith('SP')] + ['Grupo Etário']
colSelFE = [col for col in dfFE.columns] + ['Grupo Etário']
colSelFE

dfSelFE = dfFE[colSelFE].set_index('Grupo Etário')
for col in dfSelFE.columns:
    if col != 'Grupo Etário':
        dfSelFE[col] = dfSelFE[col].astype('long')#.str.replace(".", "")#.astype('long')

# dfSelFE = dfSelFE.T

In [57]:
dfSelFE

,RO - MASCULINO,AC - MASCULINO,AM - MASCULINO,RR - MASCULINO,PA - MASCULINO,AP - MASCULINO,TO - MASCULINO,MA - MASCULINO,PI - MASCULINO,CE - MASCULINO,...,ES - FEMININO,RJ - FEMININO,SP - FEMININO,PR - FEMININO,SC - FEMININO,RS - FEMININO,MS - FEMININO,MT - FEMININO,GO - FEMININO,DF - FEMININO
Grupo Etário,,,,,,,,,,,,,,,,,,,,,
"(0 - 4, 0 - 4)",71586,42476,206480,30420,366755,41039,64155,300256,121499,336102,...,140509,548521,1483786,384972,237651,345608,107071,138421,252012,100329
"(5 - 9, 5 - 9)",69560,43387,208071,28355,373651,41211,64187,300367,120959,328916,...,138812,537734,1486357,375728,227142,339418,105511,131929,254480,91892
"(10 - 14, 10 - 14)",70266,45549,203933,27243,402480,41305,67383,334635,130911,346029,...,133867,515868,1446086,367729,218251,328332,99186,131081,242481,101287
"(15 - 19, 15 - 19)",76484,47019,197868,27174,412106,42614,69580,338987,145234,366157,...,143330,558014,1531720,396227,230601,373858,101276,131744,255582,118022
"(20 - 24, 20 - 24)",79509,44217,204323,31733,415784,41958,73140,340010,146827,415584,...,155809,659464,1701929,448731,273363,422176,110382,139827,284906,126328
"(25 - 29, 25 - 29)",78871,38048,183809,33377,382715,39514,69129,296825,129267,396263,...,157794,656296,1738870,459489,292575,429436,113865,144384,295305,129515
"(30 - 34, 30 - 34)",78422,34758,170665,31403,362389,36746,65336,283326,126204,380147,...,168318,674666,1888809,448377,301175,425981,111444,144724,301927,136814
"(35 - 39, 35 - 39)",74905,32843,159925,28172,341196,32957,62308,265498,120875,347668,...,167709,705901,1946363,443789,297353,442017,111864,141970,296964,147312
"(40 - 44, 40 - 44)",66545,28431,139640,22877,299664,27963,56795,227704,111510,307151,...,155595,684994,1822081,426104,266593,404906,102843,132077,279953,137800
"(45 - 49, 45 - 49)",56831,22995,113517,17867,248902,23525,47826,183499,93629,264473,...,134337,617789,1628117,400442,244853,374148,92294,115814,246741,114163
"(50 - 54, 50 - 54)",51997,18924,94307,14335,207905,18868,41306,158430,84794,243054,...,125801,587438,1517168,388798,238948,383384,84886,102597,221423,98898
"(55 - 59, 55 - 59)",43973,14600,74524,11385,164448,14472,34073,130761,72879,210653,...,116037,564885,1407141,354699,225919,387394,77222,86653,188322,83156
"(60 - 64, 60 - 64)",33258,11434,56217,8405,131093,11020,26889,104514,58113,155310,...,100133,506991,1228204,296643,184738,343373,62249,67912,151504,65073
"(65 - 69, 65 - 69)",23038,8620,39956,5940,97428,7470,21052,82423,45604,122283,...,78423,413660,979409,237497,146058,283873,48036,49723,116263,49890
"(70 - 74, 70 - 74)",15009,6023,25993,3899,66012,4589,15239,60639,34580,97426,...,54647,312473,732830,176239,106080,217814,34557,34236,82669,35620
"(75 - 79, 75 - 79)",9093,3860,16721,2117,42858,3103,10412,41663,22844,65254,...,38129,211929,495222,121357,70570,151553,24104,22192,55072,22931
"(80 - 84, 80 - 84)",5255,2227,9299,1109,23931,1734,6698,25747,13619,42603,...,26663,148646,341634,79106,47287,104225,15549,13574,35225,14999
"(85 - 89, 85 - 89)",2327,1169,4517,467,11300,862,3337,13188,6177,19717,...,15668,87719,197189,43777,26376,62028,8252,6550,17735,7463
"(90+, 90+)",1240,740,2363,217,6034,544,1644,7956,3132,11872,...,11857,66930,144091,25838,18854,44979,4993,3835,9707,4279

In [62]:
listinha = sorted(dfSelFE.columns)
estados = []
for i,k in zip(listinha[0::2], listinha[1::2]):
    estado = i[0:2]
    estados.append(estado)
    print(f'{estado} {i} {k}')
    dfSelFE[estado] = dfSelFE[i] + dfSelFE[k]

AC AC - FEMININO AC - MASCULINO
AL AL - FEMININO AL - MASCULINO
AM AM - FEMININO AM - MASCULINO
AP AP - FEMININO AP - MASCULINO
BA BA - FEMININO BA - MASCULINO
CE CE - FEMININO CE - MASCULINO
DF DF - FEMININO DF - MASCULINO
ES ES - FEMININO ES - MASCULINO
GO GO - FEMININO GO - MASCULINO
MA MA - FEMININO MA - MASCULINO
MG MG - FEMININO MG - MASCULINO
MS MS - FEMININO MS - MASCULINO
MT MT - FEMININO MT - MASCULINO
PA PA - FEMININO PA - MASCULINO
PB PB - FEMININO PB - MASCULINO
PE PE - FEMININO PE - MASCULINO
PI PI - FEMININO PI - MASCULINO
PR PR - FEMININO PR - MASCULINO
RJ RJ - FEMININO RJ - MASCULINO
RN RN - FEMININO RN - MASCULINO
RO RO - FEMININO RO - MASCULINO
RR RR - FEMININO RR - MASCULINO
RS RS - FEMININO RS - MASCULINO
SC SC - FEMININO SC - MASCULINO
SE SE - FEMININO SE - MASCULINO
SP SP - FEMININO SP - MASCULINO
TO TO - FEMININO TO - MASCULINO

In [102]:
dfFaixas = dfSelFE[estados].T
dfFaixas = (dfFaixas.groupby((np.arange(len(dfFaixas.columns)) // 2) * 10, axis=1).sum().T
 .reset_index()
 .rename(columns={'index': 'idadeTrunc'})
 .set_index('idadeTrunc'))

In [104]:
PATH_TOWRITE = PATH_FAIXA_ETARIAS + 'faixa_etaria_processada.csv' 
dfFaixas.to_csv(PATH_TOWRITE, sep=';', encoding='utf-8')

In [103]:
dfFaixas

,AC,AL,AM,AP,BA,CE,DF,ES,GO,MA,...,PR,RJ,RN,RO,RR,RS,SC,SE,SP,TO
idadeTrunc,,,,,,,,,,,,,,,,,,,,,
0,167847,512924,810784,160755,2057896,1300206,394852,571169,1034767,1175312,...,1558622,2224713,482381,275863,114928,1403318,951046,340837,6080459,251055
10,182031,585720,787374,165454,2314781,1398652,446322,564952,1015191,1320685,...,1560494,2193282,530189,287274,106974,1437763,916491,366344,6084800,269021
20,163955,592768,775443,163812,2466610,1628036,506882,630839,1168318,1277257,...,1830783,2638726,592212,313593,123977,1721149,1152650,408474,6959603,281724
30,136541,512668,664468,141581,2443543,1505610,546707,671766,1200260,1138984,...,1763597,2692631,596648,304646,113277,1726904,1214966,385773,7664143,257329
40,104798,434249,509712,104610,2077640,1201926,473776,566373,1032265,853811,...,1604097,2476855,475584,249138,78664,1519290,1016993,314999,6690421,209621
50,68151,329709,334110,65619,1588187,970299,337786,466161,792324,606803,...,1417434,2146886,395294,187808,49390,1470842,905736,239996,5536927,150266
60,41027,214457,196193,36706,1068998,620413,204089,337291,505330,403320,...,993908,1645437,240232,111424,28083,1166751,628481,148493,4047400,95910
70,20904,116942,90937,15892,606441,372233,99777,166643,256194,224247,...,537275,888202,146715,48488,11871,650898,318719,79117,2148136,51374
80,7550,42913,32159,5914,248163,157353,36273,70718,94616,92292,...,209563,367858,60385,15539,3473,264060,120348,29527,871492,20470
90,1666,8742,6534,1430,58165,33158,6082,18140,16878,21887,...,41067,91599,14525,2687,544,61998,27072,5472,205952,3478

In [89]:
dfSexo = dfSelFE.sum(axis=0).to_frame().T

In [91]:
dfList = []
sexos = ['MASCULINO', 'FEMININO']

for sex in sexos:
    colDf = [col for col in dfSexo.columns if sex in col]
    df = dfSexo[colDf]
    colsRename = {}
    for col in colDf:
        colsRename[col] = col[0:2]
    df = df.rename(columns=colsRename)
    df['sexo'] = sex
    dfList.append(df)

In [100]:
PATH_TOWRITE = '../dados/sexo/' + 'sexo_processada.csv' 
pd.concat(dfList).set_index('sexo').to_csv(PATH_TOWRITE, sep=';', encoding='utf-8')